require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = true,
  },
  indent = { enable = true },
  ensure_installed = {
    "comment",
    "css",
    "csv",
    "diff",
    "dockerfile",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gotmpl",
    "gpg",
    "html",
    "http",
    "ini",
    "javascript",
    "jq",
    "json",
    "just",
    "kconfig",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "nginx",
    "nix",
    "python",
    "r",
    "rnoweb",
    "regex",
    "rust",
    "scss",
    "sql",
    "ssh_config",
    "terraform",
    "tmux",
    "toml",
    "tsv",
    "typescript",
    "typst",
    "udev",
    "vim",
    "xml",
    "yaml"
  },
}


